# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialMedia' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for SocialMedia
    
    #pod 'FacebookSDK'
    pod 'React', :path => '../node_modules/react-native'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
    
    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
    
end
